---
ID: "9016e456-95cb-42e9-ad58-997d6d77ae83"
Parent: "062a1e69-0bf6-4d6d-ac4f-c11d0f7dc1e1"
Template: "ee43c2f0-6277-4144-b144-8ca2cefccf12"
Path: /sitecore/system/Marketing Control Panel/Outcomes/Product Purchase
DB: master
SharedFields:
- ID: "1398896a-b1aa-420f-b5ba-693841e37a55"
  Hint: IsLiveEvent
  Type: Checkbox
  Value: 0
- ID: "33ae0e84-74a0-437f-ab2b-859dfa96f6c9"
  Hint: Points
  Value: 60
- ID: "6ae27532-bac3-42c3-b91f-b4f1f20711c0"
  Hint: Group
  Value: "{601D19B6-49D2-4461-8961-A96B4EEA76CA}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{689E2994-4656-4C58-9112-7826CB46EE69}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 299
- ID: "e4d0faf3-61e7-44d4-a921-ce5c606a8da8"
  Hint: IsSystem
  Type: Checkbox
  Value: 0
Languages:
- Language: da
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Produktkøb
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T101022Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "4674871a-2885-4504-9cde-cfba07b2fa69"
      Hint: Monetary Value Applicable
      Type: Checkbox
      Value: 0
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ac6ba888-4213-43bd-b787-d8da2b6b881f"
      Hint: Name
      Value: Produktkøb
- Language: "de-DE"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Produktkauf
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T101022Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "4674871a-2885-4504-9cde-cfba07b2fa69"
      Hint: Monetary Value Applicable
      Type: Checkbox
      Value: 0
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ac6ba888-4213-43bd-b787-d8da2b6b881f"
      Hint: Name
      Value: Produktkauf
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T101022Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "4674871a-2885-4504-9cde-cfba07b2fa69"
      Hint: Monetary Value Applicable
      Type: Checkbox
      Value: 0
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ac6ba888-4213-43bd-b787-d8da2b6b881f"
      Hint: Name
      Value: Product Purchase
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 商品の購入
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T101022Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "4674871a-2885-4504-9cde-cfba07b2fa69"
      Hint: Monetary Value Applicable
      Type: Checkbox
      Value: 0
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ac6ba888-4213-43bd-b787-d8da2b6b881f"
      Hint: Name
      Value: 商品の購入
- Language: "zh-CN"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 产品采购
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181101T101022Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "4674871a-2885-4504-9cde-cfba07b2fa69"
      Hint: Monetary Value Applicable
      Type: Checkbox
      Value: 0
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "ac6ba888-4213-43bd-b787-d8da2b6b881f"
      Hint: Name
      Value: 产品采购
