---
ID: "06d0b7ee-d0cd-4faa-a7b2-838bbe6617ce"
Parent: "a1a2a4d8-1aec-48a2-ac46-c9ad1ea38f8b"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Demo SXA Sites/LighthouseFinancial/Presentation/Rendering Variants/Promo/Default
BranchID: "a19fc87d-262d-42cf-b595-41b4262733f4"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{5DF9B10F-F5B5-4E6A-AD58-08125A701147}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f83284dd-4d05-4818-9afd-f9aa2aabecec"
