---
ID: "a239a320-bec1-469c-be87-7cfb60079b13"
Parent: "f1839ae8-91a5-4920-8de5-1ec74a5b5035"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/Cumulus/Card Signup/card_type/card_type_list/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fdaa1b87-fa93-4180-b9b3-a373d97847d5"
