---
ID: "02bb6020-825f-4d85-94be-b7ace6ce3572"
Parent: "643a85f5-c9f1-4836-b17b-35ade22d03d3"
Template: "643a85f5-c9f1-4836-b17b-35ade22d03d3"
Path: /sitecore/templates/Feature/Demo Shared/XA/Page Content/Hero/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "86fcc014-351f-47a4-a44a-ea88e5e158ec"
