---
ID: "e0fbea6a-d225-4b50-954f-63bd2e2f09a9"
Parent: "c475d203-a47a-4a4b-828a-682ac52e10f5"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 3/Other/Commerce Automation
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180628T172213Z
