---
ID: "83acec67-ca49-485d-ae35-d1dde3636638"
Parent: "67a3063b-3801-4c53-8762-acfa1cd75113"
Template: "67a3063b-3801-4c53-8762-acfa1cd75113"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/Global/Pages/Login Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "34cb36de-cca8-4eb7-9d50-607b56ce3c64"
