---
ID: "dd1620ec-139a-466c-bf1e-35776556c52d"
Parent: "8cac0316-b6d0-4fed-9760-12afdadcf1d4"
Template: "8cac0316-b6d0-4fed-9760-12afdadcf1d4"
Path: /sitecore/templates/Feature/Habitat Sites/Articles/Author/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1db08bff-1f9b-4d32-810a-7a8327e04537"
      Hint: Author Name
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180705T204602Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
