---
ID: "246ec4a9-8b59-4753-b8fd-f8108d0ffd4b"
Parent: "d311bc0f-c4c1-48ce-81b3-4b67533e2a07"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Content Finder Form/Page 3/Columns Wrapper/Field Wrapper/Question 3/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ff0490c6-e778-4177-86ac-ef7e7ffe6481"
