---
ID: "0487432e-76b3-40a6-ae7f-1e539557df67"
Parent: "3a7a131c-23e2-4614-9b69-fab668499a59"
Template: "3a7a131c-23e2-4614-9b69-fab668499a59"
Path: /sitecore/templates/Feature/Demo Shared/XA/Page Content/Rendering Parameters/Page Teaser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "62e340ad-8772-4c52-8b72-aedab05ebd72"
