---
ID: "224b5644-3b91-408f-bc46-46c1622a5681"
Parent: "233d4d7d-5bfe-4dc9-bea7-79be7f16ead4"
Template: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Path: /sitecore/templates/Branches/Project/Demo Shared SXA Sites/SitecoreDemo/XA Modules/Account/Security Settings/Security Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: /Home/register
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4cdadf7a-3637-4e19-a97c-f8b88fc1c030"
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: "/Home/forgot-password"
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value:  /Home/accountmanagement
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value:  /Home/accountmanagement
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: /Home/login
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: |
        <link linktype="internal" />
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{52054874-4767-47DC-8099-8C08BFA307AA}"
