# escape=`
ARG REGISTRY
ARG SITECORE_VERSION

FROM mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019

ARG SYSTEM_ACCESSTOKEN
ARG INTERNAL_NUGET_SOURCE

WORKDIR /build
COPY nuget.config Sitecore.Demo.Platform.sln ./
COPY src/ ./src

RUN dotnet nuget add source $env:INTERNAL_NUGET_SOURCE -n "sc-demo-packages-internal"  -u "VSTS" -p $env:SYSTEM_ACCESSTOKEN
RUN MSBuild /restore /target:Build /m:4 Sitecore.Demo.Platform.sln
