---
ID: "3186a30a-ab21-45b6-872a-c8893987fec4"
Parent: "14592221-27d2-4d4b-80ea-1a15effe021c"
Template: "14592221-27d2-4d4b-80ea-1a15effe021c"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/SitecoreDemo/Fins/Content Hub Entity Types/Content Hub Blog/__Standard Values
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "acb15046-0615-442e-a7ab-c77781129dc6"
