---
ID: "1be63e8a-dda7-4f45-b546-29fba5bc01ae"
Parent: "06830b85-c52c-4618-bd6e-c990c660e8b9"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/Demo SXA Sites/LighthouseFinancial/Settings/Datasource Configurations
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "739e60b5-4be6-4eda-8246-5be88ed3f657"
