---
ID: "d7a9a7b0-2f41-4128-80b8-bef95e35a178"
Parent: "64474624-5671-422f-ae0d-1b85168cb2a9"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 1/Content Focus/Product Spotlight
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ab299de0-062f-4b8a-a416-bde4a85a41b3"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "??????????"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "467d622b-75fe-4bf3-8384-9636b35a750a"
