---
ID: "313e5783-3059-4cb1-9284-2571ac2c204f"
Parent: "64474624-5671-422f-ae0d-1b85168cb2a9"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 1/Content Focus/Recipe
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4282002f-c5f8-4be7-a7a8-78ecbe0e5d69"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "???"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "14b88993-f2bd-4bfe-a4da-1f544d110a70"
