---
ID: "edc218fd-eafa-4e7d-a905-aa6a8ee68344"
Parent: "5ce1848f-c7ad-48d7-8c74-3ae23d206097"
Template: "5ce1848f-c7ad-48d7-8c74-3ae23d206097"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/Content Hub Entity Types/Content Hub Blog/__Standard Values
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2a0807d1-1b2d-4e0c-b37a-d7f44389c6b6"
