---
ID: "a4dbba3f-33dd-462d-89e2-51efa805e8e3"
Parent: "c6928ec4-a028-4e0b-b2c8-8bbb6e55879b"
Template: "6545c81f-c30f-4b58-97d9-ef85b890f70a"
Path: /sitecore/system/Settings/Feature/Demo Shared SXA Sites/SitecoreDemo/XA/Sitecore Demo Extensions/Configure Indexes
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 1300
- ID: "c0a5bd91-e658-46ce-b631-77ce337d8e6e"
  Hint: Script
  Value: "{15F738E4-75D8-47C6-8F00-50F3FAB96C55}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e63102f6-f5c2-41e9-993e-5ee699d8a97f"
