---
ID: "233d4d7d-5bfe-4dc9-bea7-79be7f16ead4"
Parent: "21fab834-d14b-4ca0-b1ed-a9430fb697ca"
Template: "35e75c72-4985-4e09-88c3-0eac6cd1e64f"
Path: /sitecore/templates/Branches/Project/Demo Shared SXA Sites/SitecoreDemo/XA Modules/Account/Security Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fd1f19f5-aaa1-4af5-904e-6b3c20ee570e"
