---
ID: "e6d6d0f4-e552-493f-9751-a218f8fe1ead"
Parent: "04d28ed8-196a-4327-bd4c-e7dccdd01555"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Weekly Class Signup Form/Page/Section/StateSection/State/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T191307Z
