---
ID: "b77004d7-7d60-419e-81a5-4ba7528cb957"
Parent: "0dd52ff5-010d-489e-816e-7049fc3c2cfa"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Demo SXA Sites/Global/Presentation/Rendering Variants/Page Content/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8eff7a8c-1134-4218-a616-c2dab2f2aa3b"
