---
ID: "9157a3f9-547d-4d4c-8160-e8ae50a7d13a"
Parent: "005f4227-10dc-4b5b-befd-f58daa1fa6e9"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Trainer Finder Form/Page 2/Columns Wrapper/Field Wrapper/Question2/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171121T163612Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
