---
ID: "c4fabd67-de11-4cf6-854e-9e96ce88a844"
Parent: "86c4110b-96ea-482f-a8fc-0d2f67ae554d"
Template: "86c4110b-96ea-482f-a8fc-0d2f67ae554d"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/Global/Pages/Resource Pages/Resource Base/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/document_header.png
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7622904b-6219-46dc-9768-06028c9a56cd"
