---
ID: "eb693005-3e8c-4a14-ab2e-c7f5973e23ef"
Parent: "987434ac-cb20-44e1-bb93-ab6eeb479092"
Template: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Path: /sitecore/content/Demo SXA Sites/LighthouseLifestyle/Settings/Security Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseLifestyle/home/account/register
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "02e467c9-1ec1-49ab-9b64-64b8616595fd"
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: "/sitecore/content/Demo SXA Sites/LighthouseLifestyle/home/account/forgot-password"
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseLifestyle/home/account/portal
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseLifestyle/home/account/portal
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseLifestyle/home/account
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: |
        <link text="" anchor="" linktype="internal" class="" title=""  querystring="" id="{5886C263-C45D-4CF8-8A28-9FF568BE6CAA}" />
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{75D53206-47B3-4391-BD48-75C42E5FC2CE}"
