---
ID: "78d3dcc1-33c9-4028-a100-21573eb92a28"
Parent: "f7a56f00-e12e-49ce-af4f-a92b2529618d"
Template: "f7a56f00-e12e-49ce-af4f-a92b2529618d"
Path: /sitecore/templates/Foundation/Demo Shared/Workflow/Submission Notification/__Standard Values
SharedFields:
- ID: "3cb83e5d-8b67-4ba5-9bc6-e9f122ad95cb"
  Hint: Mail Server
  Value: smtp
- ID: "a291a22b-99e2-46bb-a27b-8ec744275396"
  Hint: Type
  Value: Sitecore.Demo.Platform.Foundation.Workflow.Actions.SubmissionNotification, Sitecore.Demo.Platform.Foundation.Workflow
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0ce2e5be-4796-4470-b988-d53d369c59eb"
