---
ID: "1c2330fb-8837-46fe-b43a-449fc9d6b83e"
Parent: "f0a14786-3573-41cc-9faa-f677eb3abb3a"
Template: "fcd285da-9ab2-4c8d-b185-5a7487a9ba1b"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Presentation/Rendering Variants/Page Content/Requirements/Requirements
SharedFields:
- ID: "4753764c-c05a-4623-841b-97f85135241c"
  Hint: FieldName
  Value: Requirements
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c1a22133-2cdb-497b-ad74-860082a7a7f9"
