---
ID: "46bfcae5-341f-48cb-b963-4cb147134161"
Parent: "17a63c0b-84d1-4c41-b6f7-0bdc5a7a1a90"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Trainer Finder Form/Page 1/Columns Wrapper/Field Wrapper/Question 1/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "012841a0-8321-4d5c-9155-decac81f7569"
