---
ID: "e6d6d0f4-e552-493f-9751-a218f8fe1ead"
Parent: "04d28ed8-196a-4327-bd4c-e7dccdd01555"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Weekly Class Signup Form/Page/Section/StateSection/State/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ee91b338-c75b-42a6-8046-bf3b39ed0bf1"
