---
ID: "73b72b17-02bf-4439-86f1-d36edbab7887"
Parent: "c42e14a6-6812-418b-a9f6-f4765d60df55"
Template: "26fce9bf-0256-458d-8281-a713a5bf5520"
Path: /sitecore/content/Demo SXA Sites/LighthouseFinancial/Presentation/Cache Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "059dd1fa-ed92-461f-bfc7-e5498ed74b33"
