---
ID: "481ed3db-d0dd-49bc-8ba4-4108bf7e1580"
Parent: "c42e14a6-6812-418b-a9f6-f4765d60df55"
Template: "0339bac0-78c1-43c1-b930-f8c26a5fdf80"
Path: /sitecore/content/Demo SXA Sites/LighthouseFinancial/Presentation/Placeholder Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "352a6ef7-655e-4e51-baf8-06998ba99cd4"
