---
ID: "a39866ff-6b67-49a1-9d42-34890abb4815"
Parent: "0c21f083-63e7-4cdf-aeed-e029996b088b"
Template: "475e9026-333f-432d-a4dc-52e03b75cb6b"
Path: /sitecore/system/Marketing Control Panel/Goals/Habitat Home/Trainer Finder Complete
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Apps/32x32/Cup.png
- ID: "1398896a-b1aa-420f-b5ba-693841e37a55"
  Hint: IsLiveEvent
  Type: Checkbox
  Value: 0
- ID: "33ae0e84-74a0-437f-ab2b-859dfa96f6c9"
  Hint: Points
  Value: 15
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{689E2994-4656-4C58-9112-7826CB46EE69}"
- ID: "e4d0faf3-61e7-44d4-a921-ce5c606a8da8"
  Hint: IsSystem
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180711T174444Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        extranet\Anonymous
    - ID: "797466f5-763b-4299-b6ad-e4192bf21222"
      Hint: Description
      Value: Visitor has completed the trainer finder form
    - ID: "ac6ba888-4213-43bd-b787-d8da2b6b881f"
      Hint: Name
      Value: Trainer Finder Complete
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180711T174444Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        extranet\Anonymous
