---
ID: "e0fbea6a-d225-4b50-954f-63bd2e2f09a9"
Parent: "c475d203-a47a-4a4b-828a-682ac52e10f5"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 3/Other/Commerce Automation
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9c1bae77-d329-48d1-b5d2-275557933811"
