---
ID: "39d8a8e9-fb01-424f-ab70-e14a20fc233b"
Parent: "c475d203-a47a-4a4b-828a-682ac52e10f5"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 3/Other/Content Automation
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b66ff637-c46a-4321-8953-78b23a7739e1"
