---
ID: "d6d1ee90-a1ac-40c4-9730-cdabd0c82b56"
Parent: "4f1b779a-7d4a-4c16-bea3-0e04b86c5e45"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Content Finder Form/Page 1/Columns Wrapper/Field Wrapper/Question 1/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171121T163611Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
