---
ID: "7835daa7-6962-4bad-bab0-9f402c3f9de2"
Parent: "c2c6dd9f-8bf0-4f92-a5a4-a811a1fd3741"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Settings/Datasource Configurations
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1cc893bc-f95e-4796-8b69-156b37b6ca6b"
