---
ID: "6cd04e2f-dbd2-4f9b-8093-dc724918129e"
Parent: "aca5f454-72e4-47bc-93a8-829621eeefe4"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Weekly Fitness Report Signup/Page/Section/RunningTypeSection/Checkbox List/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6b54d01e-8cdf-4d06-9b95-9c887b305036"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "730d6b4d-d9de-4c29-8092-6a5ebb8f40ba"
