---
ID: "fa3b1c9d-71ba-4dc8-9829-a9b9f0e8f15a"
Parent: "45c8af1d-b5b7-4fa0-947a-0c7ddad32485"
Template: "45c8af1d-b5b7-4fa0-947a-0c7ddad32485"
Path: /sitecore/templates/Feature/Habitat Sites/Articles/Rendering Parameters/Author/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120629T104300
