---
ID: "ec8d04d9-acc4-4424-a3e3-bff9b8e39374"
Parent: "0e5a0dc2-78eb-4088-abb6-6c695f34ed8e"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Weekly Class Signup Form/Page/Section/FitnessActivity/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181023T193722Z
