---
ID: "a7fa7d01-1997-423a-bdd7-2eb8198cf8c0"
Parent: "14807d83-9671-4d70-b0f4-f54012f2bfb8"
Template: "14807d83-9671-4d70-b0f4-f54012f2bfb8"
Path: /sitecore/templates/Project/Habitat Sites/Habitat Home/Pages/Guide Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "23aa5741-fa6a-4add-9e79-7a752af6deb1"
      Hint: Image
      Value: |
        <image mediaid="{3651792B-489E-4A25-9B69-48219439CF2A}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180214T035808Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: 
