---
ID: "57ddda93-8c79-452e-8d7e-6f828b97f8c2"
Parent: "7e57ce9b-7895-442e-b0c8-521e7d5bd987"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Commerce Experience Accelerator/Commerce Catalog/Product Facets
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/16x16/element_selection.png
- ID: "13f89250-ad6b-4548-882e-118a12c18094"
  Hint: Parameters Template
  Value: "{FF75632A-03ED-4D31-B42A-1EEE45E5147F}"
- ID: "3d08db46-2267-41b0-bc52-be69fd618633"
  Hint: Cacheable
  Type: Checkbox
  Value: 1
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: Render
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Sitecore.HabitatHome.Website.Controllers.EmptyContentController,Sitecore.HabitatHome.Website
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product Facets
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170324T030329Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
