---
ID: "6e5b022c-3342-4f19-bf5c-d316720a27fa"
Parent: "ede537b6-698b-4b6e-b2ce-536dbdc7247a"
Template: "0339bac0-78c1-43c1-b930-f8c26a5fdf80"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Presentation/Placeholder Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ddc0d0dc-f913-41fe-a3a8-46594f925168"
