---
ID: "a0ecb671-109e-47e5-bdfc-897ba1149405"
Parent: "e8eb7605-d803-4cf8-89ba-8a3e996083a2"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Content Finder Form/Page 2/Columns Wrapper/Field Wrapper/Question2/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "bb6396ae-8e71-4cbd-9a1b-c2fa7b6daeed"
