---
ID: "046565da-f71a-453b-841c-4cb48fe8cb7d"
Parent: "a8b4e58e-f3bd-4da3-8238-7e6d50ede383"
Template: "324733cf-afec-4281-9a18-03b6cfc4e535"
Path: "/sitecore/content/Habitat Sites/Habitat Home Basic/home/Component Kitchen Sink/content-components/Data/Trainer Finder Promo"
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "14023dd5-30e7-4e3c-bf31-d835f3a87410"
      Hint: PromoText
      Value: <p>Meet Your Fitness Goals</p>
    - ID: "18f9beb8-0116-40fd-b47e-fd0a2327d7e0"
      Hint: PromoIcon
      Value: |
        <image mediaid="{D590210C-4B80-4014-B82E-3DD16DB7331C}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180607T205412Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "b59adc09-32a3-46f2-aede-b0c633979263"
      Hint: PromoText2
      Value: <p>We offer a wide array of fitness subscriptions from the best in the business. Take our Trainer Finder test to match your best trainer.&nbsp;</p>
    - ID: "b8c1a9d2-de76-4519-aff4-1442525f32b0"
      Hint: PromoLink
      Value: |
        <link linktype="internal" text="Try it now" querystring="" target="" id="{3B26DAB2-CD1D-4E12-8FF8-FB8603213B8D}" />
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "14023dd5-30e7-4e3c-bf31-d835f3a87410"
      Hint: PromoText
      Value: <p>Meet Your Fitness Goals</p>
    - ID: "18f9beb8-0116-40fd-b47e-fd0a2327d7e0"
      Hint: PromoIcon
      Value: |
        <image mediaid="{D590210C-4B80-4014-B82E-3DD16DB7331C}" />
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180618T150908Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        extranet\Anonymous
    - ID: "b59adc09-32a3-46f2-aede-b0c633979263"
      Hint: PromoText2
      Value: <p>We offer a wide array of fitness subscriptions from the best in the business. Take our Trainer Finder test to match your best trainer.&nbsp;</p>
    - ID: "b8c1a9d2-de76-4519-aff4-1442525f32b0"
      Hint: PromoLink
      Value: |
        <link linktype="internal" text="Try it now" querystring="" target="" id="{3B26DAB2-CD1D-4E12-8FF8-FB8603213B8D}" />
