---
ID: "6e325452-cc21-4ab0-b705-67e50b02f325"
Parent: "4fded342-b304-42f7-8091-ae3eb660ba4c"
Template: "4fded342-b304-42f7-8091-ae3eb660ba4c"
Path: /sitecore/templates/Feature/Demo Shared/Forms/PatternCardActionMapping/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2cd4679d-c90b-4178-8ad5-1083ab4445e1"
    - ID: "ecb328c3-8f41-4c0b-8fdf-a01096146f3b"
      Hint: Mapped Value
      Value: $name
