---
ID: "cf1d13ad-0d42-4a0e-aaa8-b59d5ad7c0f2"
Parent: "df2221c3-332b-455d-9ee5-b0d0d328c557"
Template: "98600d25-458e-450a-b9fa-fe8460bdbc3b"
Path: /sitecore/content/SFMC Tenant/Tenant Service Settings/Pipeline Context Builders/JObject Contact to Sync Settings Pipeline Context Plugin Builder
DB: master
BranchID: "30fceba1-f89c-4419-81ac-7c91ca2e55a9"
SharedFields:
- ID: "0fd8f7e4-75ce-4e56-88fb-8d46bbba5447"
  Hint: PluginReaders
  Type: Treelist
  Value: "{A8FDDF08-0094-49E0-AFF2-9EE01672EAAB}"
- ID: "1dc5cf69-b957-4f1a-b31d-c0d80f6eec09"
  Hint: ValueTransformer
  Value: "{C058E2FA-AA25-4F54-8AE5-BC0C9AFC62D4}"
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{CF1D13AD-0D42-4A0E-AAA8-B59D5AD7C0F2}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210715T123956Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Anonymous
