services:
  init:
    healthcheck:
      test: ["CMD", "powershell", "ps"]
    image: ${REGISTRY}demo/lighthouse-init:${SITECORE_VERSION}-linux-${DEMO_VERSION}
    build:
      context: ./images/windows/demo-init
      dockerfile: Dockerfile.linux
      args:
        BUILD_IMAGE: mcr.microsoft.com/dotnet/sdk:3.1-alpine
        BASE_IMAGE: mcr.microsoft.com/dotnet/runtime:3.1-alpine
    environment:
      ADMIN_PASSWORD: ${SITECORE_ADMIN_PASSWORD}
      ADMIN_USER_NAME: "superuser"
      HOST_CD: "http://cd"
      HOST_CM: "http://cm"
      HOST_ID: "http://id"
      MARKETING_DEFINITIONS_APIKEY: ${MARKETING_DEFINITIONS_APIKEY}