---
ID: "a6d1a51c-a150-4b10-b4b2-ae87ce8aa4a9"
Parent: "e6d899c8-1620-4c4d-94b0-af076f3499f8"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 2/Other/Commerce Automation
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180628T172145Z
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Commerce オートメーション
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190125T064424Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
