---
ID: "69615339-62cd-41b1-8c45-c52b23b299d5"
Parent: "11919030-63b2-49d2-950f-427fe600fa77"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseFinancial/Lighthouse Credit Card Application/Page/Dropdown List/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "deb5f200-13be-4046-ba1f-09e944d03a76"
