---
ID: "7459851b-cf6a-45b5-b1a8-cbacfd060362"
Parent: "1f90a020-4014-44ee-b86d-b07ce89892af"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Trainer Finder Form/Page 1/Columns Wrapper/Field Wrapper/Question 1/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e440a581-02ac-4ff1-8068-bf2d15ccb506"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "97620abd-0d0d-49ac-9817-0664ca8acaa5"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 設定
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fcf0082a-e1a7-4b2d-acaf-4566df79dec9"
