---
ID: "fbc9ec49-2831-4e2d-a898-f5269e87a8bc"
Parent: "248ac2ae-be96-4763-be80-6c63848f7a9e"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/Cumulus/Card Signup/get_started/age_list/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4d142f8c-b254-4dc4-9b36-4efb4006293b"
