---
ID: "705abaae-c6a7-41ae-a5ba-883ced9d5c4e"
Parent: "2325b50c-9de9-47e5-a432-1f983e9fa3f8"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Content Finder Form/Page 2/Columns Wrapper/Field Wrapper/Question2/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "03974df6-ca6a-45d4-bbc8-a11925ce5990"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "be561647-e819-42bd-9b4a-aece330aef8d"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 設定
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "de68092d-331c-47de-a422-4bbaec19c4f6"
