---
ID: "c8a894af-f211-49f8-97f3-deceadfd5858"
Parent: "0b039d82-71d6-4498-b09d-1bba3263d75f"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Demo Shared SXA Sites/LighthouseHealthcare/Images/Services
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c18555af-af4e-42ef-aa23-0a4a640946ed"
