---
ID: "ea89c258-f47f-4a76-a9e2-df450985b897"
Parent: "7e57ce9b-7895-442e-b0c8-521e7d5bd987"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Commerce Experience Accelerator/Commerce Catalog/Product List Sorting
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Other/16x16/icon_header_sort.png
- ID: "13f89250-ad6b-4548-882e-118a12c18094"
  Hint: Parameters Template
  Value: "{0CE23E59-209C-48B2-93C5-7372D83FD667}"
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Feature/Commerce Experience Accelerator/Catalog/Datasource/Product List Sorting
- ID: "94069f66-609c-48b0-8281-521c30fb269d"
  Hint: Open Properties after Add
  Value: 
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: "query:./ancestor::*[@@templatename='Site']/Data/Commerce/Catalog"
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: Render
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Sitecore.Demo.Platform.Website.Controllers.EmptyContentController,Sitecore.Demo.Platform.Website
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Product List Sorting
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f25396db-9471-436e-a206-17b44c72abb2"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 商品リスト ソート
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5b734065-ae88-4d4a-9b68-5c64e0a10c99"
