---
ID: "64b12137-c6ce-423d-b29c-9bd7ead1d76e"
Parent: "7e57ce9b-7895-442e-b0c8-521e7d5bd987"
Template: "2a3e91a0-7987-44b5-ab34-35c2d9de83b9"
Path: /sitecore/layout/Renderings/Feature/Commerce Experience Accelerator/Commerce Catalog/Product Bundle
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Office/16x16/elements3.png
- ID: "13f89250-ad6b-4548-882e-118a12c18094"
  Hint: Parameters Template
  Value: "{059E844A-819B-4C35-9B15-519C769D40D3}"
- ID: "1a7c85e5-dc0b-490d-9187-bb1dbcb4c72f"
  Hint: Datasource Template
  Value: /sitecore/templates/Feature/Commerce Experience Accelerator/Catalog/Datasource/Product Bundle
- ID: "b5b27af1-25ef-405c-87ce-369b3a004016"
  Hint: Datasource Location
  Value: "query:./ancestor::*[@@templatename='Site']/Data/Commerce/Catalog"
- ID: "ded9e431-3604-4921-a4b3-a6ec7636a5b6"
  Hint: Controller Action
  Value: Render
- ID: "e64ad073-dfcc-4d20-8c0b-fe5aa6226cd7"
  Hint: Controller
  Value: Sitecore.Demo.Platform.Website.Controllers.EmptyContentController,Sitecore.Demo.Platform.Website
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2e9d6520-2472-409e-9fea-1daea919899c"
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "c58786ce-ce43-4d19-9e85-80a914919414"
