# escape=`

ARG SOLUTION_XCONNECT_IMAGE
ARG SOLUTION_CONTENT_IMAGE

ARG BASE_IMAGE

FROM ${SOLUTION_CONTENT_IMAGE} as content
FROM ${SOLUTION_XCONNECT_IMAGE} as xconnect

FROM $BASE_IMAGE

COPY security/ /solution/db/security
COPY --from=content /solution/cm /solution/cm
COPY --from=content /solution/cd /solution/cd
COPY --from=content /solution/src /solution/src
COPY --from=xconnect /solution/xconnect /solution/xconnect
