---
ID: "a678156d-2f69-432c-9a88-d240eea6dbf9"
Parent: "ec31a1f7-e539-4e4f-b1ae-49705c227a1f"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Weekly Fitness Report Signup/Page/Section/StateSection/State/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "030f42f6-9f45-4714-93f9-8b4fe1093652"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aa0ff0fe-a581-4321-8458-eb0ee2693b8f"
