---
ID: "4c9dee2f-29f1-4628-93c4-723c3599a019"
Parent: "816e892b-9542-49b5-b9d2-8de9a7a64ebc"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/Cumulus/Card Signup/get_started/citizen_list/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3b94e8d9-b04c-4c51-b1a8-0ff88b759cbf"
