---
ID: "b1641500-778c-48d9-8a37-6976e85c7681"
Parent: "16ef3c02-9be4-4fe5-9c71-e0985bd4a049"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Content Finder Form/Page 3/Columns Wrapper/Field Wrapper/Question 3/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "85cf6a13-01b8-4083-ad11-dddb409163cd"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "371e69ea-7b81-418e-9134-8b43623c2afc"
