---
ID: "f9286742-35a5-4209-b3b2-ae0f8ea0bf2d"
Parent: "3cbbe139-0a83-4d00-92d7-67fdc83efbf3"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Weekly Fitness Report Signup/Page/Section/Country/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "100726de-1a55-4753-8bd1-1921b8eaa117"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "84addfdc-ae26-4ca0-9782-013b1fce4393"
