---
ID: "b7afcc86-364d-4eb1-9ff8-e8bda4a7cecb"
Parent: "84ff7d07-a948-4c9c-a173-f90c26e433af"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Presentation/Rendering Variants/Page Content/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b856a8c4-a350-4e01-aa22-61f6aa8ab660"
