---
ID: "f0a14786-3573-41cc-9faa-f677eb3abb3a"
Parent: "84ff7d07-a948-4c9c-a173-f90c26e433af"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Presentation/Rendering Variants/Page Content/Requirements
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce44300c-8d15-4d3d-a842-238d7d998505"
