---
ID: "8d967bcc-4486-46ee-badb-b47e0b97298e"
Parent: "84ff7d07-a948-4c9c-a173-f90c26e433af"
Template: "fb3e3034-33f8-4ce8-be98-dd05010f4c22"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Presentation/Rendering Variants/Page Content/Services
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f4b78a23-3ad8-4b6f-92dd-6c3f0ac8849e"
