---
ID: "b624f40f-8f6f-414f-a364-6e54d9a7657a"
Parent: "7d8101bf-f300-4611-9072-c87de29b5386"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Content And Product Finder Form/Page 2/Columns Wrapper/Field Wrapper/Question2/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9160b937-b2f7-449d-b739-bf86149b08a5"
