---
ID: "c385da28-0ba3-4c5b-b320-9db2eeb5b61d"
Parent: "ec72f1a0-1ef5-49cd-8cd9-1095a2801475"
Template: "ec72f1a0-1ef5-49cd-8cd9-1095a2801475"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/Content Hub Entity Types/Content Hub Webinar/__Standard Values
SharedFields:
- ID: "c9283d9e-7c29-4419-9c28-5a5c8ff53e84"
  Hint: __Bucketable
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "527aa542-bde5-4598-a1fc-2dd93c91f54e"
