---
ID: "1f678f26-cc6d-49ab-8323-1d79e8534910"
Parent: "afeca1d9-8eae-4e48-95df-e50f52ee2fbc"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Weekly Class Signup Form/Page/Section/RunningTypeSection/Checkbox List/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "342a3eba-2a20-4f8c-88a8-514a30d384fc"
