---
ID: "5939abdb-7531-4821-a68e-377780a72157"
Parent: "ec27159a-a568-4695-8616-5dec8e30abde"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/Cumulus/Card Signup/get_started/customer_list/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "71413ca5-ba61-4c75-beef-0f54156a64f6"
