---
ID: "fa3da82b-5d69-4aea-ac5a-38b038bda71a"
Parent: "3ba23a0c-a049-4b74-be52-24a3d53272ba"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Trainer Finder Form/Page 3/Columns Wrapper/Field Wrapper/Question 3/Settings
Languages:
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b44c246e-64dc-4aae-b39f-a9ae631a1fa2"
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ef03aa10-2381-4d7c-a172-007b42cdf2ed"
