---
ID: "2263a1d1-2d54-4a16-964d-44ec0714f774"
Parent: "0075ef06-e295-40ba-8f73-bf14b9acf1d1"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Trainer Finder Form/Page 2/Columns Wrapper/Field Wrapper/Question2/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a575c5f4-032a-4154-a390-477e88f687eb"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a0fd506a-65c2-409e-8057-afbbe0e6b30f"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 設定
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7a3ed5ba-781a-4ee2-a8c7-2e767f9ce90c"
