---
ID: "8dbd70db-b85f-4bb7-85e8-1d79e01bb49f"
Parent: "cb5e16df-b01c-44a0-a4d6-c99235acf860"
Template: "cb5e16df-b01c-44a0-a4d6-c99235acf860"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/Global/Pages/Account Page/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d6a5e3a0-0b1c-454f-8c75-1b4c0aa2aebd"
