---
ID: "f65089dc-2f1c-4db9-9c85-f4625549ecfe"
Parent: "5c6d0d54-a8ec-41d1-a5c0-518fe375197c"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Content Finder Form/Page 1/Columns Wrapper/Field Wrapper/Question 1/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "58bbf021-6fd6-41d6-9753-429c9914cc2d"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "17c1b2e1-75da-4fc1-b900-1a5d1053c36d"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: 設定
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce75d769-c147-4dfa-988c-a8d0d3bb2d5a"
