---
ID: "85b5a992-703a-47c2-9b38-52c6a52855fc"
Parent: "f4e54f06-fe90-4d8a-ade7-cabc76036530"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Weekly Fitness Report Signup/Page/Section/CyclingTypeSection/Checkbox List/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "58f5e55d-84a1-4587-a7ba-ae4e445fce03"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "99b359a6-73f7-4353-b3fc-e156446122fc"
