---
ID: "a6d1a51c-a150-4b10-b4b2-ae87ce8aa4a9"
Parent: "e6d899c8-1620-4c4d-94b0-af076f3499f8"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 2/Other/Commerce Automation
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e75c2285-7df6-4f65-b7a0-bc02b53e1965"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "Commerce ????????"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fa7f8035-475c-48d2-96f0-5eb9823f1d38"
