---
ID: "3593270b-e249-4587-9b1c-16ae5172b38b"
Parent: "e6d899c8-1620-4c4d-94b0-af076f3499f8"
Template: "68b0cf3c-9150-4db7-acab-f626e59bca6d"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign facet 2/Other/Content Automation
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8e61f0a6-04f1-43f5-9cbe-12a5c2129766"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "????? ????????"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b63cc167-3206-485c-9a77-79a55a317955"
