---
ID: "11d8e2a5-a6a7-4bc8-b442-14243fdb4ad8"
Parent: "a63b941d-6d80-489a-ba43-2dd3e2cea103"
Template: "bd74a392-dacd-4c23-853a-d520762b33a1"
Path: "/sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/your-health/trainer-finder"
DB: master
SharedFields:
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Type: Checklist
  Value: "{D063E9D1-C7B5-4B1E-B31E-69886C9C59F5}"
- ID: "97fb669d-5b8e-4829-9a24-06418c315d73"
  Hint: SxaTags
  Value: "{A076B3E0-6D6F-4308-B1DC-20DC506D55AD}"
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{C6EBE5E6-BCE3-4BAB-A5F9-16382F8369FE}"
- ID: "b0a67b2a-8b07-4e0b-8809-69f751709806"
  Hint: __Tracking
  Type: Tracking
  Value: |
    <tracking>
      <profile
        id="3b752260-57e2-488c-9d84-95a8a5171af8"
        name="Health Focus"
        presets="fitness fanatic|100||">
        <key
          name="Children"
          value="0" />
        <key
          name="Cooking"
          value="0" />
        <key
          name="Exercise"
          value="10" />
        <key
          name="Fitness Tech"
          value="10" />
        <key
          name="Mental Health"
          value="5" />
        <key
          name="Nutrition"
          value="10" />
      </profile>
    </tracking>
- ID: "db51d4e9-c24d-4670-af0e-62c8aa08e2b6"
  Hint: LocalData
  Value: "{2032492C-D28C-4A6A-8900-02CAF26FA03F}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:p="p" xmlns:s="s"
      p:p="1">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
        <r
          uid="{E04B0C05-FF09-4BF2-8C35-F4B655D682E7}"
          p:before="*"
          s:ds=""
          s:id="{6AB4EE29-CB78-4DCE-A316-3E6C3D5513F5}"
          s:par="Styles=%7bF825A291-5E8E-4A92-89DC-81C72AC7EED8%7d&amp;DynamicPlaceholderId=3&amp;Caching=0%7c0%7c0%7c0%7c0%7c0%7c0%7c0"
          s:ph="/main/sxa-content-container/container-1/container-4" />
        <r
          uid="{28CDBB97-4912-4869-92D3-4B0BA39A7241}"
          p:after="r[@uid='{E04B0C05-FF09-4BF2-8C35-F4B655D682E7}']"
          s:ds="{510EB70E-8DE5-454F-BC4E-A2DC6C43EF58}"
          s:id="{6B5B0FE6-5C85-4487-BA7E-F8C2ECC186A8}"
          s:par=""
          s:ph="/main/sxa-content-container/container-1/container-4/sitecoreFormsWrapper-3" />
        <r
          uid="{43CE0CAA-587D-4AEF-B672-B651F54F3EE6}"
          p:after="r[@uid='{28CDBB97-4912-4869-92D3-4B0BA39A7241}']"
          s:ds="local:/Data/Hero - Find A Trainer"
          s:id="{6BCF8D8E-0A28-4844-BFB4-96C852BAD2DC}"
          s:par="GridParameters=%7b113BEF7C-97E6-46CA-8CF3-916F7FAA8DE2%7d&amp;DynamicPlaceholderId=2&amp;Caching=0%7c0%7c0%7c0%7c0%7c0%7c0%7c0"
          s:ph="/main/sxa-content-container/container-1" />
        <r
          uid="{A63CC628-3632-41A9-9E37-363B286B62E1}"
          p:after="*[1=2]"
          s:id="{896A2C68-1362-4E88-8BA0-1805AE6D4837}"
          s:par="GridParameters=%7bF2FCE948-4F77-44AF-A188-B2030061F793%7d&amp;DynamicPlaceholderId=4"
          s:ph="/main/sxa-content-container/container-1" />
      </d>
    </r>
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Trainer Finder
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180319T210227Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{E93E190F-3398-489D-B3A3-A3B0D9BB33C5}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Trainer Finder
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a3555ef5-6619-441d-b4db-da3fd5f9c770"
      Hint: Navigation Image
      Value: 
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Trainer Finder
  - Version: 2
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180319T210227Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{E93E190F-3398-489D-B3A3-A3B0D9BB33C5}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Trainer Finder
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a3555ef5-6619-441d-b4db-da3fd5f9c770"
      Hint: Navigation Image
      Value: 
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Trainer Finder
  - Version: 3
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180319T210227Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{E93E190F-3398-489D-B3A3-A3B0D9BB33C5}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Trainer Finder
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a3555ef5-6619-441d-b4db-da3fd5f9c770"
      Hint: Navigation Image
      Value: |
        <image mediaid="{AB96E599-DB37-429C-ACCA-309814FA9333}" />
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Trainer Finder
  - Version: 4
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{28CDBB97-4912-4869-92D3-4B0BA39A7241}"
              s:ds="{EB4A36E9-149B-4E2E-A391-2E9F36AA0897}" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180319T210227Z
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{E93E190F-3398-489D-B3A3-A3B0D9BB33C5}"
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Trainer Finder
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a3555ef5-6619-441d-b4db-da3fd5f9c770"
      Hint: Navigation Image
      Value: |
        <image mediaid="{AB96E599-DB37-429C-ACCA-309814FA9333}" />
    - ID: "e2a634fd-5177-46de-b629-5393caed77d7"
      Hint: Title
      Value: Trainer Finder
- Language: "fr-CA"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Trainer Finder
  Versions:
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Trainer Finder
  Versions:
