---
ID: "3729f1cb-f39e-43f3-8f81-433e439f1ccf"
Parent: "b367156b-18c2-4010-91ab-ac9fbdbb9237"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Content And Product Finder Form/Page 1/Columns Wrapper/Field Wrapper/Question 1/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f2ba398a-a48e-4cf1-a92f-922b8c4fce30"
