---
ID: "ab47a6d6-ae0e-4d0c-8ffb-b0c6ab6da83b"
Parent: "45f79f7c-63d0-49f7-b9fe-d8f11357766c"
Template: "1e5bfa08-0e32-4156-927e-930392fdcb92"
Path: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/Settings/Security Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171208T035457Z
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: 
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: 
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: 
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: 
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: 
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: 
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{75D53206-47B3-4391-BD48-75C42E5FC2CE}"
  - Version: 2
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171208T035457Z
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: 
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: 
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: 
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: 
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: 
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: 
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{75D53206-47B3-4391-BD48-75C42E5FC2CE}"
  - Version: 3
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171208T035457Z
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account/register
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: "/sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account/forgot-password"
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account/portal
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account/portal
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: |
        <link id="{AF767BB8-D6AE-469B-A548-01CC911C1B5D}" querystring="" text="" anchor="" url="/Demo SXA Sites/LighthouseHealthcare/Data/Emails/Forgot Password" title="" class="" linktype="internal" />
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{75D53206-47B3-4391-BD48-75C42E5FC2CE}"
  - Version: 4
    Fields:
    - ID: "202eaae4-33b3-4db1-9170-4de88a27e7cd"
      Hint: User Profile
      Value: "{BCBF635A-9C02-4EFE-85FB-19358FAEAAB2}"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171208T035457Z
    - ID: "81b370b0-9ea6-435d-be15-fcffb1cec57f"
      Hint: Register Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account/register
    - ID: "927f708e-ab61-44ab-ab09-2a1a23e07e05"
      Hint: Forgot Password Page
      Value: "/sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account/forgot-password"
    - ID: "a98f8b72-64aa-4a9c-90db-92f7aead55ad"
      Hint: Accounts Details Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account/portal
    - ID: "b8937bfd-64c0-4abe-8e64-b328ea3f1ea1"
      Hint: After Login Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account/portal
    - ID: "e90c6342-5bc9-4011-a3c5-eed1fca7eb7c"
      Hint: Login Page
      Value: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/home/account
    - ID: "f2f9cc39-fda5-4a19-82da-d03699d8f1be"
      Hint: Forgot Password Email Template
      Value: |
        <link id="{AF767BB8-D6AE-469B-A548-01CC911C1B5D}" querystring="" text="" anchor="" url="/Demo SXA Sites/LighthouseHealthcare/Data/Emails/Forgot Password" title="" class="" linktype="internal" />
    - ID: "f48206df-d2eb-4df2-9ac0-18a2e9c31f29"
      Hint: Register Outcome
      Value: "{75D53206-47B3-4391-BD48-75C42E5FC2CE}"
