# escape=`
ARG BASE_IMAGE

FROM $BASE_IMAGE

# SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# COPY temp/App_Data/jobs/continuous/IndexWorker /inetpub/wwwroot/