---
ID: "a70a2c9b-5614-4192-afaf-fc45e9014f82"
Parent: "b576031f-56f5-465a-95c8-5cb9893f0946"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Demo Shared SXA Sites/LighthouseLifestyle/Images/Trainers
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "043e3ab7-6961-4ee3-a33c-5202e6e8ce34"
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "552bd214-4add-4cc5-912d-6bef2ca0e9dd"
