---
ID: "7b69e094-fd16-4989-8758-c80100548db7"
Parent: "673d2a71-17e6-4ce9-9f1d-b70e85d3955b"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/SitecoreDemo/Fins/Verticals/Fins/ServicesPage/Content/Requirements
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Rich Text
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "66cb6760-6aff-47fc-8e8f-a9e1171e3a19"
