---
ID: "fa3b1c9d-71ba-4dc8-9829-a9b9f0e8f15a"
Parent: "45c8af1d-b5b7-4fa0-947a-0c7ddad32485"
Template: "45c8af1d-b5b7-4fa0-947a-0c7ddad32485"
Path: /sitecore/templates/Feature/Demo Shared/XA/Articles/Rendering Parameters/Author/__Standard Values
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b9a19e84-f67e-4f57-a395-a91514da2f12"
