---
ID: "68a9912d-3b4c-4078-ba20-5a9c42f83a37"
Parent: "45f79f7c-63d0-49f7-b9fe-d8f11357766c"
Template: "f86fe270-00a4-492f-bfaf-5bf27e40ce13"
Path: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/Settings/Datasource Configurations
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fb8ffb8f-294f-46ee-ad65-62cf43abf350"
  - Version: 2
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "dd4fb208-afc4-4217-a30e-aa08bf7a8915"
  - Version: 3
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9a43cf7d-361f-4ba7-9625-5b44a0e5aa7c"
  - Version: 4
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "984ff73b-0abf-4b59-a242-df1f746d95c3"
