---
ID: "e2272222-63e6-4091-bbe7-adf825d6b817"
Parent: "eea2a34f-00da-4635-9988-0d951b753c89"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Demo Shared SXA Sites/LighthouseLifestyle/Product Media
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "753dbaef-6b69-4b50-a1b2-1c3c7cb90292"
- Language: "ja-JP"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "151af9f3-b3a2-4646-b907-a26d91e4b4d7"
