---
ID: "df4ffc8a-43d8-4fc2-a41c-30d21c07a168"
Parent: "eea2a34f-00da-4635-9988-0d951b753c89"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/Demo Shared SXA Sites/LighthouseLifestyle/Product Thumbnails
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 350
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4c994db1-e12e-427f-ae14-76ff09a19150"
