---
ID: "b3001b6e-d0ff-4440-b76b-d680702604ba"
Parent: "5adab0db-bd92-4993-bb08-82c132449eea"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseLifestyle/Content And Product Finder Form/Page 3/Columns Wrapper/Field Wrapper/Question 3/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f914f681-813c-4b26-a7be-80b394e99667"
