---
ID: "54d63273-947a-4927-b21a-0022625315e1"
Parent: "07c0c14c-a2f3-44ff-847c-92f2e7f64c67"
Template: "8e0c1738-3591-4c60-8151-54abcc9807d1"
Path: /sitecore/system/Marketing Control Panel/Profiles/LighthouseLifestyle/Product Interests
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: "{689E2994-4656-4C58-9112-7826CB46EE69}"
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 800
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "5d9fe5d7-4c45-4a98-a1f5-4796a6da428b"
      Hint: Name
      Value: Product Interests
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ad361a9e-2f50-41e2-beb1-163b12c8eaef"
- Language: "fr-CA"
  Versions:
  - Version: 1
    Fields:
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ee683215-a75f-4598-a6c6-518b113b189a"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "?????? ?????"
  Versions:
  - Version: 1
    Fields:
    - ID: "3e431de1-525e-47a3-b6b0-1ccbec3a8c98"
      Hint: __Workflow state
      Value: "{EDCBB550-BED3-490F-82B8-7B2F14CCD26E}"
    - ID: "5d9fe5d7-4c45-4a98-a1f5-4796a6da428b"
      Hint: Name
      Value: "?????? ?????"
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ccc3c661-de15-4b9a-9b39-ba5411811e3a"
