---
ID: "a1ea5c1a-ed8f-4280-b9df-23c03905bb50"
Parent: "be2a1204-f7ba-4be3-933d-190c97496700"
Template: "be2a1204-f7ba-4be3-933d-190c97496700"
Path: /sitecore/templates/Project/Demo Shared SXA Sites/Global/Settings/__Standard Values
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "58f39777-edd8-40d3-ae21-d54f3bef67f9"
