---
ID: "4987bf95-424e-48c5-b5cd-4b54f3e62d2e"
Parent: "897f96b4-3a21-4877-9f63-8c3b7c9da4b9"
Template: "5203732f-9512-4ade-8e02-0cb085c10454"
Path: /sitecore/content/Demo SXA Sites/LighthouseFinancial/Settings/Site Grouping/LighthouseFinancial/CORS/Default
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aa08c741-1423-4669-862f-fa7b0483b2b4"
