---
ID: "dd1620ec-139a-466c-bf1e-35776556c52d"
Parent: "8cac0316-b6d0-4fed-9760-12afdadcf1d4"
Template: "8cac0316-b6d0-4fed-9760-12afdadcf1d4"
Path: /sitecore/templates/Feature/Demo Shared/XA/Articles/Author/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1db08bff-1f9b-4d32-810a-7a8327e04537"
      Hint: Author Name
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "411a359d-8127-4143-8eaa-5108c5459ad6"
