---
ID: "e1ace9d4-0ae0-48d7-a7a7-ebc05a3f8c93"
Parent: "6eaff543-a88a-4d67-bd2b-5e3ba310eae9"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Trainer Finder Form/Page 3/Columns Wrapper/Field Wrapper/Question 3/Settings
DB: master
