---
ID: "d6d1ee90-a1ac-40c4-9730-cdabd0c82b56"
Parent: "4f1b779a-7d4a-4c16-bea3-0e04b86c5e45"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: /sitecore/Forms/Demo Shared SXA Sites/LighthouseHealthcare/Healthcare Content Finder Form/Page 1/Columns Wrapper/Field Wrapper/Question 1/Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4a6fed6c-63be-4348-ba54-a6e77d21de4c"
