<#
	This script finds and copies all file with the .yml extension that are found in the source Habitat project folders to App_Data\serialization\ folder inside the build output folder.
#>

######################
# Mandatory parameters

Param(
	[parameter(Mandatory=$true)]
    [String] $ConfigurationFile
)

Function Publish-YML ([String] $configFile){

    # Find and process cake-config.json

    if (!(Test-Path $configFile)) {

        Write-Host "Configuration file '$($configFile)' not found." -ForegroundColor Red
        Write-Host  "Please ensure there is a cake-config.json configuration file at '$($configFile)'" -ForegroundColor Red
        Exit 1
    
    }

    $config = Get-Content -Raw $configFile |  ConvertFrom-Json
    if (!$config) {

        throw "Error trying to load configuration!"
    
    }

    # Copy all yml files that were generated by Unicorn into a serialization folder

    $serializationFolder = "Website\App_Data\serialization"
    Copy-Item -Path (Join-Path $config.ProjectFolder src) -Filter "*.yml" -Destination (Join-Path $config.DeployFolder $serializationFolder) -Recurse -Container

}

Publish-YML -configFile $ConfigurationFile