<#
	This script finds and copies all file with the .yml extension that are found in the source Habitat project folders to App_Data\serialization\ folder inside the build output folder.
#>

######################
# Mandatory parameters

Param(
	[parameter(Mandatory=$true)]
	[ValidateNotNullOrEmpty()]
    [String] $ConfigurationFile
)

Function Publish-YML ([String] $configFile){

	Import-Module "$($PSScriptRoot)\ProcessConfigFile\ProcessConfigFile.psm1" -Force

	$configarray     = ProcessConfigFile -Config $configFile
	$config          = $configarray[0]

    # Copy all yml files that were generated by Unicorn into a serialization folder

    $serializationFolder = "Website\HabitatHome\App_Data\serialization"
    Copy-Item -Path (Join-Path $config.ProjectFolder src) -Filter "*.yml" -Destination (Join-Path $config.DeployFolder $serializationFolder) -Recurse -Container -force

}

Publish-YML -configFile $ConfigurationFile