---
ID: "e669c22f-596e-4a96-b978-474b5f54d493"
Parent: "ab2f413c-4854-48eb-b7eb-6fd2e8142b19"
Template: "7cc96707-325d-4024-9f58-b10ce1f950d1"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign group/Commerce Automation
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "05b9ab19-60c6-4262-a3f2-bdaa09a0a049"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "Commerce ????????"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f692e519-f3f1-454c-b6c8-131798ba550d"
