---
ID: "62595c25-9ef9-448c-834f-b8e4d0b197dd"
Parent: "ab2f413c-4854-48eb-b7eb-6fd2e8142b19"
Template: "7cc96707-325d-4024-9f58-b10ce1f950d1"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign group/Content Automation
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6511fa0b-e834-46b3-a6c1-fde1dc817864"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "????? ????????"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9456553a-d833-4045-b9c8-4f0460926a03"
