---
ID: "c4bc27df-a0cc-4654-97c3-a01bf9c4f68a"
Parent: "ab2f413c-4854-48eb-b7eb-6fd2e8142b19"
Template: "7cc96707-325d-4024-9f58-b10ce1f950d1"
Path: /sitecore/system/Marketing Control Panel/Taxonomies/Campaign group/Home Automation
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "477d61e2-beaa-4f8a-805a-57cefe3e0797"
- Language: "ja-JP"
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: "??? ????????"
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "914609c9-2a11-4628-9fcb-51823674db69"
