---
ID: "5b4d8749-371d-4811-a643-6609e420291e"
Parent: "8d967bcc-4486-46ee-badb-b47e0b97298e"
Template: "fcd285da-9ab2-4c8d-b185-5a7487a9ba1b"
Path: /sitecore/content/Demo SXA Sites/Cumulus/Presentation/Rendering Variants/Page Content/Services/Services
SharedFields:
- ID: "4753764c-c05a-4623-841b-97f85135241c"
  Hint: FieldName
  Value: Services
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "fe8253fb-d92e-4f31-89eb-6f9cb3d593b2"
