---
ID: "5df3574d-6404-4c55-9a3f-e0efcf8b9093"
Parent: "35850f7d-e242-467d-870f-a275abc98228"
Template: "5996ae17-2739-49f0-a1c8-c5edbe3f0025"
Path: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/Data/Forms/Form Actions Settings/Content Finder/Interest Question Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171215T050435Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8c512534-ba02-49fc-91be-66da6e6aa1b6"
      Hint: Form Question
      Value: "{5C6D0D54-A8EC-41D1-A5C0-518FE375197C}"
