---
ID: "ae2f3baf-59cc-4fee-ae82-3a90e2b2286e"
Parent: "35850f7d-e242-467d-870f-a275abc98228"
Template: "5996ae17-2739-49f0-a1c8-c5edbe3f0025"
Path: /sitecore/content/Demo SXA Sites/LighthouseHealthcare/Data/Forms/Form Actions Settings/Content Finder/Stage Question Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171215T050435Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8c512534-ba02-49fc-91be-66da6e6aa1b6"
      Hint: Form Question
      Value: "{2325B50C-9DE9-47E5-A432-1F983E9FA3F8}"
